### PR TITLE
Added codestyle check and lint to the build action

### PR DESCRIPTION
**Pull request by matyasrichter**

### CODE REVIEW

**Comment by matyasrichter** [comment]
Hm, build failed, odd. I guess the issue is `black` version, then, because it tries to reformat quite a few files when I run it locally.

**Comment by matyasrichter** [comment]
Do you mind if I pin dev dependencies to specific versions @frankie567?

**Comment by frankie567** [comment]
I'll have a look at why this is not working! Thank you for this great addition 👍

**Comment by matyasrichter** [comment]
Must have been an issue on my end :facepalm:

**Review by yezz123 — APPROVED** [review]
That looks like a great addon to this package, what do you think about using pre-commit for linting and formatting? 🚀

**Comment by frankie567** [comment]
Thank you @matyasrichter, that's a great addition!

**Pull request merged**
