### PR TITLE
Extending generated OpenAPI docs

### PR DESCRIPTION
**Pull request by matyasrichter**
This is WIP for now, but I'd like to eventually get the generated docs into a state where a frontend dev working with an API that uses fastapi-users wouldn't need to check our documentation. The goal is to have responses included in swagger along with basic descriptions of error codes.

### CODE REVIEW

**Comment by matyasrichter** [comment]
Added response examples so that errors are documented in OpenAPI, the output in redoc looks like this:
image
and updated the markdown documentation - some of the responses were outdated.

And I added some basic tests that should (hopefully) prevent inconsistency in the future.



// The python3.7 check for this commit failed due to a network error, could you restart it, please? I think I don't have the required permissions.

**Comment by matyasrichter** [comment]
What do you think about this @frankie567 ?

**Comment by frankie567** [comment]
That's once again a super interesting addition, @matyasrichter! Thank you 🙏
 
May I suggest that `get_login_responses_success` and `get_logout_responses_success` methods on authentication classes be called `get_openapi_login_responses_success` and `get_openapi_logout_responses_success` so that we don't take them for actual API logic?

I see that the codestyle check is failing, maybe just run a `make format` to solve this.

Cheers!

**Comment by matyasrichter** [comment]
@frankie567 fixed :rocket:

**Comment by matyasrichter** [comment]
Hi, sorry to bump this merged PR, but is there an estimate for when it could be released? We'd like to have this ready for our project. @frankie567

**Comment by frankie567** [comment]
Yes, sorry, I'll prepare it!

**Pull request merged**
