### PR TITLE
#1262 Issue Continuation for AccessTokenProtocol

### PR DESCRIPTION
**Pull request by Nerixjk**
Thanks for the help @frankie567!

Replication of original fix for #1262 to the AccessTokenProtocol class.

### CODE REVIEW

**Comment by frankie567** [comment]
Ha! You know, at some point, I thought that I should also fix this one while working on the others; and obviously forgot afterwards 😅

Thank you for tackling this 🙏

**Comment by frankie567** [comment]
@all-contributors add @Nerixjk for bug, code

**Comment by mattaw** [comment]
Could you release v12.1.2 with this in?

**Comment by frankie567** [comment]
Released: https://github.com/fastapi-users/fastapi-users/releases/tag/v12.1.2

**Pull request merged**
