### PR TITLE
Allow lifetime_seconds=None

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by frankie567** [comment]
Hi @davidbrochart! Thank you for this, that's indeed possible to set `lifetime_seconds` as `None`.

However, it means that the token will be valid **forever**, unless you change the secret. That's okay if you know what you are doing, but it may be a bit dangerous.

Would you mind updating the doc here to add a warning about this:

https://github.com/fastapi-users/fastapi-users/blob/d469bace6eb51e12271705d066c80c498e6b0c7b/docs/configuration/authentication/strategies/jwt.md?plain=1#L19

To:

```md
* `lifetime_seconds` (`Optional[int]`): The lifetime of the token in seconds. Can be set to `None` but in this case the token will be valid **forever**; which may raise serious security concerns.
```

**Comment by davidbrochart** [comment]
Done, thanks! And happy new year :tada:

**Comment by frankie567** [comment]
Thank you! Happy new year, David 😄

**Comment by frankie567** [comment]
@all-contributors add @davidbrochart for code

**Pull request merged**
